service: django
app: django
org: mc001

provider:
  name: aws
  runtime: python3.8
  timeout: 30

plugins:
  - serverless-python-requirements
  - serverless-wsgi

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

custom:
  wsgi:
    app: manage.app
    packRequirements: false
  pythonRequirements:
    dockerFile: ./Dockerfile
